add_newline = false
command_timeout = 1000

[line_break]
disabled = true

[aws]
disabled = false
format = 'on [$symbol$profile]($style) '
force_display = true
[aws.region_aliases]
ap-northeast-1 = 'tokyo'

[gcloud]
disabled = true
format = 'on [$account(@$domain)(\($project\))]($style) '

[golang]
symbol = " "
disabled = true

[directory]
truncation_length = 80
truncation_symbol = ""
style = "white"

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
disabled = false

# [git_metrics]
# disabled = false
# added_style = "green"
# deleted_style = "red"

[kubernetes]
disabled=false
symbol = ""
contexts = [
  { context_pattern = "arn:aws:eks:(.*):638870566973:cluster/main-(.*)", context_alias = "$2-dev" },
  { context_pattern = "arn:aws:eks:(.*):740855071960:cluster/main-(.*)", context_alias = "$2-prod" },
  { context_pattern = "arn:aws:eks:(.*):486439528070:cluster/main-(.*)", context_alias = "$2-qa" },
  { context_pattern = "satoki-(.*)@(.*)", context_alias = "satoki-$1" },
  ]

[gradle]
disabled = true

[java]
disabled = true

[bun]
disabled = true

[package]
disabled = true

